c_stdlib_version:                                   # [(osx and x86_64) or linux]
  - '10.15'                                         # [osx and x86_64]
  - "2.28"                                          # [linux]
github_actions_labels:          # [linux or (osx and arm64)]
- cirun-openstack-cpu-large     # [linux]
- cirun-macos-m4-large          # [osx and arm64]
MACOSX_SDK_VERSION:  # [osx and x86_64]
  - "11.0"           # [osx and x86_64]

# void creating spurious jobs due to multiple global pins for the package we're building here
nodejs:
  - "*"
